<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED !== true) die();

$this->setFrameMode(true);?>

<div class="contacts-container">
	<?//ELEMENTS//?>			
	<?$APPLICATION->IncludeComponent("bitrix:news.list", "contacts",
		array(
			"DISPLAY_DATE" => $arParams["DISPLAY_DATE"],
			"DISPLAY_NAME" => $arParams["DISPLAY_NAME"],
			"DISPLAY_PICTURE" => $arParams["DISPLAY_PICTURE"],
			"DISPLAY_PREVIEW_TEXT" => $arParams["DISPLAY_PREVIEW_TEXT"],
			"AJAX_MODE" => $arParams["AJAX_MODE"],
			"IBLOCK_TYPE" => $arParams["IBLOCK_TYPE"],
			"IBLOCK_ID" => $arParams["IBLOCK_ID"],
			"NEWS_COUNT" => $arParams["NEWS_COUNT"],
			"SORT_BY1" => $arParams["SORT_BY1"],
			"SORT_ORDER1" => $arParams["SORT_ORDER1"],
			"SORT_BY2" => $arParams["SORT_BY2"],
			"SORT_ORDER2" => $arParams["SORT_ORDER2"],
			"FILTER_NAME" => $arParams["FILTER_NAME"],
			"FIELD_CODE" => $arParams["LIST_FIELD_CODE"],
			"PROPERTY_CODE" => $arParams["LIST_PROPERTY_CODE"],
			"CHECK_DATES" => $arParams["CHECK_DATES"],
			"DETAIL_URL" => $arParams["DETAIL_URL"],
			"PREVIEW_TRUNCATE_LEN" => $arParams["PREVIEW_TRUNCATE_LEN"],
			"ACTIVE_DATE_FORMAT" => $arParams["LIST_ACTIVE_DATE_FORMAT"],
			"SET_TITLE" => "N",
			"SET_BROWSER_TITLE" => $arParams["SET_BROWSER_TITLE"],
			"SET_META_KEYWORDS" => $arParams["SET_META_KEYWORDS"],
			"SET_META_DESCRIPTION" => $arParams["SET_META_DESCRIPTION"],
			"SET_LAST_MODIFIED" => $arParams["SET_LAST_MODIFIED"],
			"INCLUDE_IBLOCK_INTO_CHAIN" => $arParams["INCLUDE_IBLOCK_INTO_CHAIN"],
			"ADD_SECTIONS_CHAIN" => $arParams["ADD_SECTIONS_CHAIN"],
			"HIDE_LINK_WHEN_NO_DETAIL" => $arParams["HIDE_LINK_WHEN_NO_DETAIL"],
			"PARENT_SECTION" => $arResult["VARIABLES"]["SECTION_ID"],
			"PARENT_SECTION_CODE" => $arResult["VARIABLES"]["SECTION_CODE"],
			"INCLUDE_SUBSECTIONS" => $arParams["INCLUDE_SUBSECTIONS"],
			"CACHE_TYPE" => $arParams["CACHE_TYPE"],
			"CACHE_TIME" => $arParams["CACHE_TIME"],
			"CACHE_FILTER" => $arParams["CACHE_FILTER"],
			"CACHE_GROUPS" => $arParams["CACHE_GROUPS"],
			"DISPLAY_TOP_PAGER" => $arParams["DISPLAY_TOP_PAGER"],
			"DISPLAY_BOTTOM_PAGER" => $arParams["DISPLAY_BOTTOM_PAGER"],
			"PAGER_TITLE" => $arParams["PAGER_TITLE"],
			"PAGER_SHOW_ALWAYS" => $arParams["PAGER_SHOW_ALWAYS"],
			"PAGER_TEMPLATE" => $arParams["PAGER_TEMPLATE"],
			"PAGER_DESC_NUMBERING" => $arParams["PAGER_DESC_NUMBERING"],
			"PAGER_DESC_NUMBERING_CACHE_TIME" => $arParams["PAGER_DESC_NUMBERING_CACHE_TIME"],
			"PAGER_SHOW_ALL" => $arParams["PAGER_SHOW_ALL"],
			"PAGER_BASE_LINK_ENABLE" => $arParams["PAGER_BASE_LINK_ENABLE"],
			"SET_STATUS_404" => $arParams["SET_STATUS_404"],
			"SHOW_404" => $arParams["SHOW_404"],
			"MESSAGE_404" => $arParams["MESSAGE_404"],
			"PAGER_BASE_LINK" => $arParams["PAGER_BASE_LINK"],
			"PAGER_PARAMS_NAME" => $arParams["PAGER_PARAMS_NAME"],
			"AJAX_OPTION_JUMP" => $arParams["AJAX_OPTION_JUMP"],
			"AJAX_OPTION_STYLE" => $arParams["AJAX_OPTION_STYLE"],
			"AJAX_OPTION_HISTORY" => $arParams["AJAX_OPTION_HISTORY"],
			"AJAX_OPTION_ADDITIONAL" => $arParams["AJAX_OPTION_ADDITIONAL"],
			"OBJECTS_IBLOCK_ID" => $arParams["OBJECTS_IBLOCK_ID"]
		),
		$component
	);?>

	<?//DESCRIPTION//?>
	<?$APPLICATION->IncludeComponent("bitrix:main.include", "description",
		array(
			"AREA_FILE_SHOW" => "file",
			"PATH" => SITE_DIR."include/contacts_description.php"
		),
		$component
	);?>

	<?//OBJECTS//
	if($arParams["SHOW_OBJECTS"] != "N") {
		$GLOBALS["arContactsObjectsFilter"] = array("!PROPERTY_SHOW_IN_CONTACTS" => false);?>
		<?$APPLICATION->IncludeComponent("bitrix:news.list", "objects",
			array(
				"IBLOCK_TYPE" => $arParams["OBJECTS_IBLOCK_TYPE"],
				"IBLOCK_ID" => $arParams["OBJECTS_IBLOCK_ID"],
				"NEWS_COUNT" => $arParams["OBJECTS_NEWS_COUNT"],
				"SORT_BY1" => $arParams["OBJECTS_SORT_BY1"],
				"SORT_ORDER1" => $arParams["OBJECTS_SORT_ORDER1"],
				"SORT_BY2" => $arParams["OBJECTS_SORT_BY2"],
				"SORT_ORDER2" => $arParams["OBJECTS_SORT_ORDER2"],
				"FILTER_NAME" => "arContactsObjectsFilter",
				"FIELD_CODE" => array(),
				"PROPERTY_CODE" => $arParams["OBJECTS_PROPERTY_CODE"],
				"CHECK_DATES" => "Y",
				"DETAIL_URL" => "",
				"AJAX_MODE" => "",
				"AJAX_OPTION_SHADOW" => "",
				"AJAX_OPTION_JUMP" => "",
				"AJAX_OPTION_STYLE" => "",
				"AJAX_OPTION_HISTORY" => "",
				"CACHE_TYPE" => $arParams["CACHE_TYPE"],
				"CACHE_TIME" => $arParams["CACHE_TIME"],
				"CACHE_FILTER" => $arParams["CACHE_FILTER"],
				"CACHE_GROUPS" => $arParams["CACHE_GROUPS"],
				"PREVIEW_TRUNCATE_LEN" => "",
				"ACTIVE_DATE_FORMAT" => "",
				"DISPLAY_PANEL" => "",
				"SET_TITLE" => "N",
				"SET_BROWSER_TITLE" => "N",
				"SET_META_KEYWORDS" => "N",
				"SET_META_DESCRIPTION" => "N",
				"SET_STATUS_404" => "N",
				"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
				"ADD_SECTIONS_CHAIN" => "",
				"HIDE_LINK_WHEN_NO_DETAIL" => "",
				"PARENT_SECTION" => "",
				"PARENT_SECTION_CODE" => "",
				"DISPLAY_NAME" => "",
				"DISPLAY_DATE" => "",
				"DISPLAY_TOP_PAGER" => "N",
				"DISPLAY_BOTTOM_PAGER" => "Y",
				"PAGER_SHOW_ALWAYS" => "",
				"PAGER_TEMPLATE" => "arrows",
				"PAGER_DESC_NUMBERING" => "",
				"PAGER_DESC_NUMBERING_CACHE_TIME" => "",
				"PAGER_SHOW_ALL" => "",
				"AJAX_OPTION_ADDITIONAL" => "",
				"ITEMS_TITLE" => $arParams["OBJECTS_TITLE"],
				"SHOW_PROMOTIONS" => $arParams["OBJECTS_SHOW_PROMOTIONS"],
				"PROMOTIONS_IBLOCK_ID" => $arParams["PROMOTIONS_IBLOCK_ID"],
				"CATALOG_IBLOCK_ID" => $arParams["CATALOG_IBLOCK_ID"],
				"USE_REVIEW" => $arParams["OBJECTS_USE_REVIEW"],
				"REVIEWS_IBLOCK_ID" => $arParams["OBJECTS_REVIEWS_IBLOCK_ID"]
			),
			$component,
			array("HIDE_ICONS" => "Y")
		);?>
	<?}?>
</div>